### PR TITLE
Fix notebooks and saved a rendered version

### PR DESCRIPTION
**Pull request by fspaolo**
Adding my revised notebooks to the IS2HW repo.

### CODE REVIEW

**Review by jomey — COMMENTED** [review]
Fernando,

can you please redo your last commit and remove all the dot-files under the `data` directory.
I see a lot of them and they don't seem relevant for this.

I will update the `.gitignore` file for this repository as soon as Amy's PR #9  is in, so these files will not be committed going forward.

Thank you.

**Comment by fspaolo** [comment]
@jomey you can try now (I don't know how those dot files ended up there)

**Comment by jomey** [comment]
Did you push your changes?
I still see them under the 'Files changed' tab in this PR.

**Comment by fspaolo** [comment]
Yes, I don't know what happened (using a cellphone hotspot). I see the changes now.

**Comment by jomey** [comment]
See them as well.

There is one last dot files with the folder `.ipynp_checkpoints`. Mind taking care of that too?

In master I added that to the `.gitignore`

**Comment by fspaolo** [comment]
Done.

**Comment by dshean** [comment]
Hi @fspaolo.  Catching up after vacation... 
Looks like you included large data files (~160 MB) in the pull request?  Did you ever figure out the aws pull for these?  Would be better to store externally, rather than including in the repo.

**Comment by dshean** [comment]
@jomey, can you test and modify the notebooks/instructions to pull the large data files from s3, and remove from this PR?  @fspaolo experienced issues with this.

**Comment by fspaolo** [comment]
@jomey There are two cells that list and download files from s3... but I have issues accessing the s3 URL from my machine.

**Comment by jomey** [comment]
@fspaolo - OK, I will have a look.

To reduce the size of this branch again, however, we need to first completely remove the commit, where you added the data files.

Could you please edit the commit and force push to this PR again?

**Comment by jomey** [comment]
I am also happy to create a new PR and we abandon this branch

**Comment by fspaolo** [comment]
@jomey Please do the latter (and I will remove the files from my commits from now on).

**Comment by jomey** [comment]
Closing this in favor of #11

**Pull request closed without merging**
